[package]
name = "sha256"
version = "0.1.0"
authors = ["kmolski <starfighter413@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rayon = "1.5.1"

[profile.release]
debug = true
